"""add remaining models and new columns

Revision ID: fde2475b2fc9
Revises: d0d45027667d
Create Date: 2026-05-18 23:32:35.693906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fde2475b2fc9'
down_revision = 'd0d45027667d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cita_planificada',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('auditoria_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('creador_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('duracion_min', sa.Integer(), nullable=False),
    sa.Column('lugar', sa.String(length=300), nullable=True),
    sa.Column('creada_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['auditoria_id'], ['auditoria.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creador_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_actuacion',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('auditoria_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('objetivo_general', sa.Text(), nullable=True),
    sa.Column('objetivo_brecha_pct', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('plazo_meses', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('aprobado_por', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('aprobado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aprobado_por'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['auditoria_id'], ['auditoria.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auditoria_id')
    )
    op.create_table('tarea',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('auditoria_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('creador_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('asignado_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('prioridad', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('completada_en', sa.DateTime(), nullable=True),
    sa.Column('creada_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asignado_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['auditoria_id'], ['auditoria.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creador_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valoracion_puesto',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('auditoria_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('nombre_puesto', sa.String(length=160), nullable=False),
    sa.Column('grupo_profesional', sa.String(length=140), nullable=True),
    sa.Column('factor_formacion', sa.SmallInteger(), nullable=False),
    sa.Column('factor_condiciones', sa.SmallInteger(), nullable=False),
    sa.Column('factor_esfuerzo', sa.SmallInteger(), nullable=False),
    sa.Column('factor_responsabilidad', sa.SmallInteger(), nullable=False),
    sa.Column('puntuacion_total', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('n_ocupantes', sa.Integer(), nullable=True),
    sa.Column('n_hombres', sa.Integer(), nullable=True),
    sa.Column('n_mujeres', sa.Integer(), nullable=True),
    sa.Column('salario_medio_h', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salario_medio_m', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('brecha_puesto_pct', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['auditoria_id'], ['auditoria.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerta', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=mysql.ENUM('RIESGO_CRITICO', 'BRECHA_ALTA', 'ANOMALIA', 'AUDITORIA_VENCIDA', 'RECOMENDACION', 'SISTEMA', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('severidad',
               existing_type=mysql.ENUM('INFO', 'WARNING', 'ERROR', 'CRITICO', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'INFO'"))
        batch_op.alter_column('canal',
               existing_type=mysql.ENUM('EMAIL', 'SISTEMA', 'AMBOS', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'AMBOS'"))

    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=mysql.ENUM('PENDIENTE', 'PROCESANDO', 'REVISION', 'COMPLETADA', 'ERROR', 'RECHAZADA', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDIENTE'"))
        batch_op.drop_column('finalizada_en')
        batch_op.drop_column('procesada_en')
        batch_op.drop_column('nivel_riesgo_global')
        batch_op.drop_column('notas')

    with op.batch_alter_table('auditoria_archivo', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=mysql.ENUM('EXCEL_ORIGEN', 'WORD_TECNICO', 'PDF_EJECUTIVO', 'CSV_PROCESADO', 'OTRO', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.drop_column('tam_bytes')
        batch_op.drop_column('mime')
        batch_op.drop_column('hash_sha256')

    with op.batch_alter_table('auditoria_recomendacion', schema=None) as batch_op:
        batch_op.alter_column('prioridad',
               existing_type=mysql.ENUM('BAJA', 'MEDIA', 'ALTA', 'URGENTE', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'MEDIA'"))
        batch_op.alter_column('meses_estimados',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.SmallInteger(),
               existing_nullable=True)

    with op.batch_alter_table('dimension', schema=None) as batch_op:
        batch_op.alter_column('orden',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.SmallInteger(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('recomendacion_catalogo', schema=None) as batch_op:
        batch_op.alter_column('meses_default',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.SmallInteger(),
               existing_nullable=True)

    with op.batch_alter_table('resultado', schema=None) as batch_op:
        batch_op.alter_column('nivel_riesgo',
               existing_type=mysql.ENUM('BAJO', 'MEDIO', 'ALTO', 'CRITICO', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               existing_nullable=True)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_usuario_empresa'), 'empresa', ['empresa_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_usuario_rol'), 'rol', ['rol_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('idx_usuario_rol'), ['rol_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_usuario_empresa'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_usuario_activo'), ['activo'], unique=False)
        batch_op.drop_column('must_change_password')

    with op.batch_alter_table('sector', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_sector_codigo'), ['codigo'], unique=False)

    with op.batch_alter_table('resultado', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_resultado_auditoria'), 'auditoria', ['auditoria_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_resultado_dimension'), 'dimension', ['dimension_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('idx_resultado_riesgo'), ['nivel_riesgo'], unique=False)
        batch_op.create_index(batch_op.f('idx_resultado_dimension'), ['dimension_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_resultado_brecha'), ['brecha_media_pct'], unique=False)
        batch_op.create_index(batch_op.f('idx_resultado_auditoria'), ['auditoria_id'], unique=False)
        batch_op.alter_column('nivel_riesgo',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('BAJO', 'MEDIO', 'ALTO', 'CRITICO', collation='utf8mb4_unicode_ci'),
               existing_nullable=True)

    with op.batch_alter_table('recomendacion_catalogo', schema=None) as batch_op:
        batch_op.alter_column('meses_default',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(unsigned=True),
               existing_nullable=True)

    with op.batch_alter_table('estadisticas_sectoriales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_est_dimension'), 'dimension', ['dimension_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_est_sector'), 'sector', ['sector_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('uq_sector_dim_anio'), ['sector_id', 'dimension_id', 'dimension_valor', 'anio'], unique=True)
        batch_op.create_index(batch_op.f('idx_sector_periodo'), ['sector_id', 'anio'], unique=False)
        batch_op.create_index(batch_op.f('idx_sector_brecha'), ['brecha_media_pct'], unique=False)

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_empresa_sector'), 'sector', ['sector_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_empresa_sector'), ['sector_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_empresa_activa'), ['activa'], unique=False)

    with op.batch_alter_table('dimension', schema=None) as batch_op:
        batch_op.alter_column('orden',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(unsigned=True),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('auditoria_recomendacion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_aud_reco_catalogo'), 'recomendacion_catalogo', ['recomendacion_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_aud_reco_auditoria'), 'auditoria', ['auditoria_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('uq_auditoria_reco'), ['auditoria_id', 'recomendacion_id'], unique=True)
        batch_op.create_index(batch_op.f('idx_aud_reco_prioridad'), ['prioridad'], unique=False)
        batch_op.create_index(batch_op.f('idx_aud_reco_aplicada'), ['aplicada'], unique=False)
        batch_op.alter_column('meses_estimados',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('prioridad',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('BAJA', 'MEDIA', 'ALTA', 'URGENTE', collation='utf8mb4_unicode_ci'),
               existing_nullable=False,
               existing_server_default=sa.text("'MEDIA'"))

    with op.batch_alter_table('auditoria_evento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_evento_auditoria'), 'auditoria', ['auditoria_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_evento_usuario'), 'usuario', ['usuario_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_evento_fecha'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('idx_evento_auditoria'), ['auditoria_id'], unique=False)

    with op.batch_alter_table('auditoria_archivo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash_sha256', mysql.CHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True))
        batch_op.add_column(sa.Column('mime', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120), nullable=True))
        batch_op.add_column(sa.Column('tam_bytes', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_archivo_auditoria'), 'auditoria', ['auditoria_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_archivo_tipo'), ['tipo'], unique=False)
        batch_op.create_index(batch_op.f('idx_archivo_auditoria'), ['auditoria_id'], unique=False)
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=30),
               type_=mysql.ENUM('EXCEL_ORIGEN', 'WORD_TECNICO', 'PDF_EJECUTIVO', 'CSV_PROCESADO', 'OTRO', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)

    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notas', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.add_column(sa.Column('nivel_riesgo_global', mysql.ENUM('BAJO', 'MEDIO', 'ALTO', 'CRITICO', collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.add_column(sa.Column('procesada_en', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('finalizada_en', mysql.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_auditoria_cliente'), 'usuario', ['cliente_usuario_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_auditoria_empresa'), 'empresa', ['empresa_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_auditoria_auditor'), 'usuario', ['auditor_usuario_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_auditoria_riesgo'), ['nivel_riesgo_global'], unique=False)
        batch_op.create_index(batch_op.f('idx_auditoria_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('idx_auditoria_empresa'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_auditoria_auditor'), ['auditor_usuario_id'], unique=False)
        batch_op.alter_column('estado',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('PENDIENTE', 'PROCESANDO', 'REVISION', 'COMPLETADA', 'ERROR', 'RECHAZADA', collation='utf8mb4_unicode_ci'),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDIENTE'"))

    with op.batch_alter_table('anomalia', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_anomalia_dimension'), 'dimension', ['dimension_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_anomalia_auditoria'), 'auditoria', ['auditoria_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_anomalia_severidad'), ['severidad'], unique=False)
        batch_op.create_index(batch_op.f('idx_anomalia_revisada'), ['revisada'], unique=False)
        batch_op.create_index(batch_op.f('idx_anomalia_auditoria'), ['auditoria_id'], unique=False)

    with op.batch_alter_table('alerta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_alerta_auditoria'), 'auditoria', ['auditoria_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_alerta_usuario'), 'usuario', ['usuario_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_alerta_empresa'), 'empresa', ['empresa_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_alerta_usuario'), ['usuario_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_alerta_tipo'), ['tipo'], unique=False)
        batch_op.create_index(batch_op.f('idx_alerta_no_enviada'), ['enviada', 'leida'], unique=False)
        batch_op.create_index(batch_op.f('idx_alerta_empresa'), ['empresa_id'], unique=False)
        batch_op.alter_column('canal',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('EMAIL', 'SISTEMA', 'AMBOS', collation='utf8mb4_unicode_ci'),
               existing_nullable=False,
               existing_server_default=sa.text("'AMBOS'"))
        batch_op.alter_column('severidad',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('INFO', 'WARNING', 'ERROR', 'CRITICO', collation='utf8mb4_unicode_ci'),
               existing_nullable=False,
               existing_server_default=sa.text("'INFO'"))
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=40),
               type_=mysql.ENUM('RIESGO_CRITICO', 'BRECHA_ALTA', 'ANOMALIA', 'AUDITORIA_VENCIDA', 'RECOMENDACION', 'SISTEMA', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)

    op.drop_table('valoracion_puesto')
    op.drop_table('tarea')
    op.drop_table('plan_actuacion')
    op.drop_table('cita_planificada')
    # ### end Alembic commands ###
