"""Relacion Empresa-Auditor

Revision ID: dc69984d921f
Revises: fde2475b2fc9
Create Date: 2026-05-25 20:29:07.262228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc69984d921f'
down_revision = 'fde2475b2fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa_auditor',
    sa.Column('empresa_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('usuario_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('empresa_id', 'usuario_id')
    )
    with op.batch_alter_table('alerta', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=mysql.ENUM('RIESGO_CRITICO', 'BRECHA_ALTA', 'ANOMALIA', 'AUDITORIA_VENCIDA', 'RECOMENDACION', 'SISTEMA', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('severidad',
               existing_type=mysql.ENUM('INFO', 'WARNING', 'ERROR', 'CRITICO', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'INFO'"))
        batch_op.alter_column('canal',
               existing_type=mysql.ENUM('EMAIL', 'SISTEMA', 'AMBOS', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'AMBOS'"))
        batch_op.drop_index(batch_op.f('idx_alerta_empresa'))
        batch_op.drop_index(batch_op.f('idx_alerta_no_enviada'))
        batch_op.drop_index(batch_op.f('idx_alerta_tipo'))
        batch_op.drop_index(batch_op.f('idx_alerta_usuario'))
        batch_op.drop_constraint(batch_op.f('fk_alerta_empresa'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_alerta_auditoria'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_alerta_usuario'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['usuario_id'], ['id'])
        batch_op.create_foreign_key(None, 'auditoria', ['auditoria_id'], ['id'])
        batch_op.create_foreign_key(None, 'empresa', ['empresa_id'], ['id'])

    with op.batch_alter_table('anomalia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_anomalia_auditoria'))
        batch_op.drop_index(batch_op.f('idx_anomalia_revisada'))
        batch_op.drop_index(batch_op.f('idx_anomalia_severidad'))
        batch_op.drop_constraint(batch_op.f('fk_anomalia_auditoria'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_anomalia_dimension'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'dimension', ['dimension_id'], ['id'])
        batch_op.create_foreign_key(None, 'auditoria', ['auditoria_id'], ['id'])

    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=mysql.ENUM('PENDIENTE', 'PROCESANDO', 'REVISION', 'COMPLETADA', 'ERROR', 'RECHAZADA', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDIENTE'"))
        batch_op.drop_index(batch_op.f('idx_auditoria_auditor'))
        batch_op.drop_index(batch_op.f('idx_auditoria_empresa'))
        batch_op.drop_index(batch_op.f('idx_auditoria_estado'))
        batch_op.drop_index(batch_op.f('idx_auditoria_riesgo'))
        batch_op.drop_constraint(batch_op.f('fk_auditoria_empresa'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_auditoria_cliente'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_auditoria_auditor'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['cliente_usuario_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuario', ['auditor_usuario_id'], ['id'])
        batch_op.create_foreign_key(None, 'empresa', ['empresa_id'], ['id'])
        batch_op.drop_column('nivel_riesgo_global')
        batch_op.drop_column('finalizada_en')
        batch_op.drop_column('notas')
        batch_op.drop_column('procesada_en')

    with op.batch_alter_table('auditoria_archivo', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=mysql.ENUM('EXCEL_ORIGEN', 'WORD_TECNICO', 'PDF_EJECUTIVO', 'CSV_PROCESADO', 'DOCUMENTO_ADICIONAL', 'OTRO', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=30),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_archivo_auditoria'))
        batch_op.drop_index(batch_op.f('idx_archivo_tipo'))
        batch_op.drop_constraint(batch_op.f('fk_archivo_auditoria'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'auditoria', ['auditoria_id'], ['id'])
        batch_op.drop_column('mime')
        batch_op.drop_column('hash_sha256')
        batch_op.drop_column('tam_bytes')

    with op.batch_alter_table('auditoria_evento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_evento_auditoria'))
        batch_op.drop_index(batch_op.f('idx_evento_fecha'))
        batch_op.drop_constraint(batch_op.f('fk_evento_auditoria'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_evento_usuario'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'auditoria', ['auditoria_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuario', ['usuario_id'], ['id'])

    with op.batch_alter_table('auditoria_recomendacion', schema=None) as batch_op:
        batch_op.alter_column('prioridad',
               existing_type=mysql.ENUM('BAJA', 'MEDIA', 'ALTA', 'URGENTE', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'MEDIA'"))
        batch_op.alter_column('meses_estimados',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.SmallInteger(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_aud_reco_aplicada'))
        batch_op.drop_index(batch_op.f('idx_aud_reco_prioridad'))
        batch_op.drop_index(batch_op.f('uq_auditoria_reco'))
        batch_op.drop_constraint(batch_op.f('fk_aud_reco_catalogo'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_aud_reco_auditoria'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'auditoria', ['auditoria_id'], ['id'])
        batch_op.create_foreign_key(None, 'recomendacion_catalogo', ['recomendacion_id'], ['id'])

    with op.batch_alter_table('chat_mensaje', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_chat_auditoria'))
        batch_op.drop_index(batch_op.f('idx_chat_autor'))
        batch_op.drop_index(batch_op.f('idx_chat_fecha'))
        batch_op.drop_constraint(batch_op.f('fk_chat_autor'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_chat_auditoria'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'auditoria', ['auditoria_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'usuario', ['autor_id'], ['id'])

    with op.batch_alter_table('cita_planificada', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_cita_auditoria'))
        batch_op.drop_index(batch_op.f('idx_cita_creador'))
        batch_op.drop_index(batch_op.f('idx_cita_fecha'))
        batch_op.drop_constraint(batch_op.f('fk_cita_auditoria'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_cita_creador'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'auditoria', ['auditoria_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'usuario', ['creador_id'], ['id'])

    with op.batch_alter_table('dimension', schema=None) as batch_op:
        batch_op.alter_column('orden',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.SmallInteger(),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_empresa_activa'))
        batch_op.drop_index(batch_op.f('idx_empresa_sector'))
        batch_op.drop_constraint(batch_op.f('fk_empresa_sector'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sector', ['sector_id'], ['id'])

    with op.batch_alter_table('estadisticas_sectoriales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_sector_brecha'))
        batch_op.drop_index(batch_op.f('idx_sector_periodo'))
        batch_op.drop_index(batch_op.f('uq_sector_dim_anio'))
        batch_op.drop_constraint(batch_op.f('fk_est_sector'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_est_dimension'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sector', ['sector_id'], ['id'])
        batch_op.create_foreign_key(None, 'dimension', ['dimension_id'], ['id'])

    with op.batch_alter_table('plan_actuacion', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=mysql.ENUM('BORRADOR', 'ACTIVO', 'COMPLETADO', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'BORRADOR'"))
        batch_op.drop_index(batch_op.f('idx_plan_estado'))
        batch_op.drop_constraint(batch_op.f('fk_plan_aprobador'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_plan_auditoria'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['aprobado_por'], ['id'])
        batch_op.create_foreign_key(None, 'auditoria', ['auditoria_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('recomendacion_catalogo', schema=None) as batch_op:
        batch_op.alter_column('meses_default',
               existing_type=mysql.TINYINT(unsigned=True),
               type_=sa.SmallInteger(),
               existing_nullable=True)

    with op.batch_alter_table('resultado', schema=None) as batch_op:
        batch_op.alter_column('nivel_riesgo',
               existing_type=mysql.ENUM('BAJO', 'MEDIO', 'ALTO', 'CRITICO', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_resultado_auditoria'))
        batch_op.drop_index(batch_op.f('idx_resultado_brecha'))
        batch_op.drop_index(batch_op.f('idx_resultado_dimension'))
        batch_op.drop_index(batch_op.f('idx_resultado_riesgo'))
        batch_op.drop_constraint(batch_op.f('fk_resultado_dimension'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_resultado_auditoria'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'dimension', ['dimension_id'], ['id'])
        batch_op.create_foreign_key(None, 'auditoria', ['auditoria_id'], ['id'])

    with op.batch_alter_table('sector', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_sector_codigo'))

    with op.batch_alter_table('tarea', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=mysql.ENUM('TAREA', 'HITO', 'REUNION', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'TAREA'"))
        batch_op.alter_column('prioridad',
               existing_type=mysql.ENUM('BAJA', 'MEDIA', 'ALTA', 'URGENTE', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'MEDIA'"))
        batch_op.alter_column('estado',
               existing_type=mysql.ENUM('PENDIENTE', 'EN_PROGRESO', 'COMPLETADA', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDIENTE'"))
        batch_op.drop_index(batch_op.f('idx_tarea_asignado'))
        batch_op.drop_index(batch_op.f('idx_tarea_auditoria'))
        batch_op.drop_index(batch_op.f('idx_tarea_creador'))
        batch_op.drop_index(batch_op.f('idx_tarea_estado'))
        batch_op.drop_index(batch_op.f('idx_tarea_fechas'))
        batch_op.drop_constraint(batch_op.f('fk_tarea_auditoria'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tarea_creador'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tarea_asignado'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['creador_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuario', ['asignado_id'], ['id'])
        batch_op.create_foreign_key(None, 'auditoria', ['auditoria_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_usuario_activo'))
        batch_op.drop_index(batch_op.f('idx_usuario_empresa'))
        batch_op.drop_index(batch_op.f('idx_usuario_rol'))
        batch_op.drop_constraint(batch_op.f('fk_usuario_rol'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_usuario_empresa'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'empresa', ['empresa_id'], ['id'])
        batch_op.create_foreign_key(None, 'rol', ['rol_id'], ['id'])
        batch_op.drop_column('telefono')

    with op.batch_alter_table('valoracion_puesto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_vpt_auditoria'))
        batch_op.drop_index(batch_op.f('idx_vpt_puntuacion'))
        batch_op.drop_constraint(batch_op.f('fk_vpt_auditoria'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'auditoria', ['auditoria_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valoracion_puesto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_vpt_auditoria'), 'auditoria', ['auditoria_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_vpt_puntuacion'), ['puntuacion_total'], unique=False)
        batch_op.create_index(batch_op.f('idx_vpt_auditoria'), ['auditoria_id'], unique=False)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_usuario_empresa'), 'empresa', ['empresa_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_usuario_rol'), 'rol', ['rol_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('idx_usuario_rol'), ['rol_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_usuario_empresa'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_usuario_activo'), ['activo'], unique=False)

    with op.batch_alter_table('tarea', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tarea_asignado'), 'usuario', ['asignado_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_tarea_creador'), 'usuario', ['creador_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_tarea_auditoria'), 'auditoria', ['auditoria_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_tarea_fechas'), ['fecha_inicio', 'fecha_fin'], unique=False)
        batch_op.create_index(batch_op.f('idx_tarea_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('idx_tarea_creador'), ['creador_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_tarea_auditoria'), ['auditoria_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_tarea_asignado'), ['asignado_id'], unique=False)
        batch_op.alter_column('estado',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('PENDIENTE', 'EN_PROGRESO', 'COMPLETADA', collation='utf8mb4_unicode_ci'),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDIENTE'"))
        batch_op.alter_column('prioridad',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('BAJA', 'MEDIA', 'ALTA', 'URGENTE', collation='utf8mb4_unicode_ci'),
               existing_nullable=False,
               existing_server_default=sa.text("'MEDIA'"))
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=30),
               type_=mysql.ENUM('TAREA', 'HITO', 'REUNION', collation='utf8mb4_unicode_ci'),
               existing_nullable=False,
               existing_server_default=sa.text("'TAREA'"))

    with op.batch_alter_table('sector', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_sector_codigo'), ['codigo'], unique=False)

    with op.batch_alter_table('resultado', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_resultado_auditoria'), 'auditoria', ['auditoria_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_resultado_dimension'), 'dimension', ['dimension_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('idx_resultado_riesgo'), ['nivel_riesgo'], unique=False)
        batch_op.create_index(batch_op.f('idx_resultado_dimension'), ['dimension_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_resultado_brecha'), ['brecha_media_pct'], unique=False)
        batch_op.create_index(batch_op.f('idx_resultado_auditoria'), ['auditoria_id'], unique=False)
        batch_op.alter_column('nivel_riesgo',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('BAJO', 'MEDIO', 'ALTO', 'CRITICO', collation='utf8mb4_unicode_ci'),
               existing_nullable=True)

    with op.batch_alter_table('recomendacion_catalogo', schema=None) as batch_op:
        batch_op.alter_column('meses_default',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(unsigned=True),
               existing_nullable=True)

    with op.batch_alter_table('plan_actuacion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_plan_auditoria'), 'auditoria', ['auditoria_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_plan_aprobador'), 'usuario', ['aprobado_por'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_plan_estado'), ['estado'], unique=False)
        batch_op.alter_column('estado',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('BORRADOR', 'ACTIVO', 'COMPLETADO', collation='utf8mb4_unicode_ci'),
               existing_nullable=False,
               existing_server_default=sa.text("'BORRADOR'"))

    with op.batch_alter_table('estadisticas_sectoriales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_est_dimension'), 'dimension', ['dimension_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_est_sector'), 'sector', ['sector_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('uq_sector_dim_anio'), ['sector_id', 'dimension_id', 'dimension_valor', 'anio'], unique=True)
        batch_op.create_index(batch_op.f('idx_sector_periodo'), ['sector_id', 'anio'], unique=False)
        batch_op.create_index(batch_op.f('idx_sector_brecha'), ['brecha_media_pct'], unique=False)

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_empresa_sector'), 'sector', ['sector_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_empresa_sector'), ['sector_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_empresa_activa'), ['activa'], unique=False)

    with op.batch_alter_table('dimension', schema=None) as batch_op:
        batch_op.alter_column('orden',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(unsigned=True),
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('cita_planificada', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_cita_creador'), 'usuario', ['creador_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_cita_auditoria'), 'auditoria', ['auditoria_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_cita_fecha'), ['fecha_hora'], unique=False)
        batch_op.create_index(batch_op.f('idx_cita_creador'), ['creador_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_cita_auditoria'), ['auditoria_id'], unique=False)

    with op.batch_alter_table('chat_mensaje', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_chat_auditoria'), 'auditoria', ['auditoria_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_chat_autor'), 'usuario', ['autor_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_chat_fecha'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('idx_chat_autor'), ['autor_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_chat_auditoria'), ['auditoria_id'], unique=False)

    with op.batch_alter_table('auditoria_recomendacion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_aud_reco_auditoria'), 'auditoria', ['auditoria_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_aud_reco_catalogo'), 'recomendacion_catalogo', ['recomendacion_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_index(batch_op.f('uq_auditoria_reco'), ['auditoria_id', 'recomendacion_id'], unique=True)
        batch_op.create_index(batch_op.f('idx_aud_reco_prioridad'), ['prioridad'], unique=False)
        batch_op.create_index(batch_op.f('idx_aud_reco_aplicada'), ['aplicada'], unique=False)
        batch_op.alter_column('meses_estimados',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('prioridad',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('BAJA', 'MEDIA', 'ALTA', 'URGENTE', collation='utf8mb4_unicode_ci'),
               existing_nullable=False,
               existing_server_default=sa.text("'MEDIA'"))

    with op.batch_alter_table('auditoria_evento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_evento_usuario'), 'usuario', ['usuario_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_evento_auditoria'), 'auditoria', ['auditoria_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_evento_fecha'), ['creado_en'], unique=False)
        batch_op.create_index(batch_op.f('idx_evento_auditoria'), ['auditoria_id'], unique=False)

    with op.batch_alter_table('auditoria_archivo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tam_bytes', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hash_sha256', mysql.CHAR(collation='utf8mb4_unicode_ci', length=64), nullable=True))
        batch_op.add_column(sa.Column('mime', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_archivo_auditoria'), 'auditoria', ['auditoria_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_archivo_tipo'), ['tipo'], unique=False)
        batch_op.create_index(batch_op.f('idx_archivo_auditoria'), ['auditoria_id'], unique=False)
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=30),
               type_=mysql.ENUM('EXCEL_ORIGEN', 'WORD_TECNICO', 'PDF_EJECUTIVO', 'CSV_PROCESADO', 'DOCUMENTO_ADICIONAL', 'OTRO', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)

    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('procesada_en', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('notas', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.add_column(sa.Column('finalizada_en', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('nivel_riesgo_global', mysql.ENUM('BAJO', 'MEDIO', 'ALTO', 'CRITICO', collation='utf8mb4_unicode_ci'), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_auditoria_auditor'), 'usuario', ['auditor_usuario_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_auditoria_cliente'), 'usuario', ['cliente_usuario_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_auditoria_empresa'), 'empresa', ['empresa_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_auditoria_riesgo'), ['nivel_riesgo_global'], unique=False)
        batch_op.create_index(batch_op.f('idx_auditoria_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('idx_auditoria_empresa'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_auditoria_auditor'), ['auditor_usuario_id'], unique=False)
        batch_op.alter_column('estado',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('PENDIENTE', 'PROCESANDO', 'REVISION', 'COMPLETADA', 'ERROR', 'RECHAZADA', collation='utf8mb4_unicode_ci'),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDIENTE'"))

    with op.batch_alter_table('anomalia', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_anomalia_dimension'), 'dimension', ['dimension_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_anomalia_auditoria'), 'auditoria', ['auditoria_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_anomalia_severidad'), ['severidad'], unique=False)
        batch_op.create_index(batch_op.f('idx_anomalia_revisada'), ['revisada'], unique=False)
        batch_op.create_index(batch_op.f('idx_anomalia_auditoria'), ['auditoria_id'], unique=False)

    with op.batch_alter_table('alerta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_alerta_usuario'), 'usuario', ['usuario_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_alerta_auditoria'), 'auditoria', ['auditoria_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_alerta_empresa'), 'empresa', ['empresa_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_alerta_usuario'), ['usuario_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_alerta_tipo'), ['tipo'], unique=False)
        batch_op.create_index(batch_op.f('idx_alerta_no_enviada'), ['enviada', 'leida'], unique=False)
        batch_op.create_index(batch_op.f('idx_alerta_empresa'), ['empresa_id'], unique=False)
        batch_op.alter_column('canal',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('EMAIL', 'SISTEMA', 'AMBOS', collation='utf8mb4_unicode_ci'),
               existing_nullable=False,
               existing_server_default=sa.text("'AMBOS'"))
        batch_op.alter_column('severidad',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('INFO', 'WARNING', 'ERROR', 'CRITICO', collation='utf8mb4_unicode_ci'),
               existing_nullable=False,
               existing_server_default=sa.text("'INFO'"))
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=40),
               type_=mysql.ENUM('RIESGO_CRITICO', 'BRECHA_ALTA', 'ANOMALIA', 'AUDITORIA_VENCIDA', 'RECOMENDACION', 'SISTEMA', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)

    op.drop_table('empresa_auditor')
    # ### end Alembic commands ###
